test: composer-verify

diff --git a/.github/workflows/composer-verify.yml b/.github/workflows/composer-verify.yml
--- a/.github/workflows/composer-verify.yml
+++ b/.github/workflows/composer-verify.yml
@@ -63,9 +63,20 @@ jobs:
             echo "phpcs not found"
             exit 1
           fi
-          mkdir target
           $PHPCS_BIN --colors --report=full
 
+      - name: phpcs_compatibilitycheck
+        run: |
+          if [ -f tools/phpcs ]; then
+           PHPCS_BIN=tools/phpcs
+           elif [ -f vendor/bin/phpcs ]; then
+            PHPCS_BIN=vendor/bin/phpcs
+           else
+            echo "phpcs not found"
+            exit 1
+          fi
+          $PHPCS_BIN --standard=./phpcs.compatibilitycheck.xml --colors --report=full
+   
       - name: phplint
         run: tools/phplint --no-progress
 
@@ -74,6 +85,9 @@ jobs:
           export XDEBUG_MODE=coverage
           tools/phpunit.phar -c phpunit.xml --log-junit var/log/phpunit-test-report.xml --coverage-cobertura phpunit-coverage.xml --coverage-text --colors=never
 
+      - name: composer_audit
+        run: composer audit
+  
       - name: Upload to Codecov
         uses: codecov/codecov-action@v2
         with:
